version: "3"

networks:
  otel-clickhouse:

services:
  otelcollector:
    image: ${OTELCOL_IMG}
    command:
      - "--config=/etc/otel-collector-contrib.yml"
      - "--set=service.telemetry.logs.level=INFO"
    volumes:
      - ./otel-collector-contrib.yml:/etc/otel-collector-contrib.yml
    ports:
      - "4317:4317"       # otlp receiver
      - "1888:1888"       # pprof extension
      - "13133:13133"     # health_check extension
      - "55679:55679"     # zpages extension
      - "24224:24224"     # fluentforwarder
      - "24224:24224/udp" # fluentforwarder
    networks:
      - otel-clickhouse
    depends_on:
      - clickhouse

  fluent-bit:
    image: fluent/fluent-bit:2.1.8
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - otelcollector
    networks:
      - otel-clickhouse

  flog:
    image: mingrammer/flog:0.4.3
    # Output fake log in JSON format
    command: [ "--format=json", "--loop", "--delay=100ms"]
    networks:
      - otel-clickhouse
    depends_on:
      - otelcollector
    logging:
      driver: fluentd
      options:
        mode: non-blocking
        # Allow time for otel-collector to spin up, then forward fluentd logs to the fluentforwarder receiver.
        fluentd-async-connect: "true"
        # Use nanosecond precision
        fluentd-sub-second-precision: "true"
    stop_signal: SIGKILL

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - otel-clickhouse

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource,vertamedia-clickhouse-datasource
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: vertamedia-clickhouse-datasource
    ports:
      - "3001:3000"
    networks:
      - otel-clickhouse