receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [logging]